---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      changed_when: no

  roles:
    - role: buluma.keyboard
      keyboard_model: pc105
      keyboard_layout: brai
      keyboard_variant: right_hand
      keyboard_options: 'lv3:alt_switch,compose:rctrl'
      keyboard_backspace: guess
